#!/usr/bin/env bash

PATH_LIST_FILE=~/.local/scripts/tmux-sessionizer-paths.txt

read_paths() {
    if [[ -f "$PATH_LIST_FILE" ]]; then
        cat "$PATH_LIST_FILE" | awk '{gsub(/^~\//, "~/")}1' | paste -sd ' ' - | sed 's|~|'"$HOME"'|g' 
    else
        echo ""
    fi
}

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find $(read_paths) -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    echo "tmux is not running, creating new session"
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    echo "tmux has-session returned null, creating new session"
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -n "$TMUX" ]]; then
    echo "Switching to session: $selected_name"
    tmux switch-client -t "$selected_name"
else
    echo "Attaching to session: $selected_name"
    tmux attach-session -t "$selected_name"
fi
